# Site settings
title: Krishna Prasad Resume | Find every thing related to Krishna Prasad, Krishna Prassad IIT Delhi
email: kprasad.iitd@gmail.com
description: Know about Krishna's prasad, resume of krishna prasad, details resume of Krishna Prasad
keywords: Krishna Prasad, Resume of Krishna's Prasad, CV Krishna Prasad, Krishna Experience
twitter_username: krishaniitd
github_username:  krishnaiitd
baseurl: "http://krishnaiitd.github.io"
